import Head from "next/head";
import Link from "next/link";
import { useAuth } from '../context/authContext';
import { useRouter } from "next/router";
import { useEffect } from "react";
import { ref, child, get  } from "firebase/database";
import {database} from '../../firebase';

export default function Collectio() {
    const { user } = useAuth();
    const paramsRouter = useRouter().query.collection;

    useEffect(() => { 
        if (paramsRouter && user) {
            const dbRef = ref(database);
            console.log("key", paramsRouter)
            get(child(dbRef, `users/${user.uid}/collections/${paramsRouter}`)).then(snapshot => {
                if (snapshot.exists()) {
                    console.log(snapshot.val());
                } else {
                    console.log("No data available");   
                }
            }).catch(error => {console.log(error)});
        }
    },[paramsRouter, user]);

    return (
        <>
            <Head>
                <title>Colección</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            
            
        </>
    )
}