import Head from "next/head";
import Link from "next/link";
import Image from 'next/image';
import { useAuth } from '../../components/context/authContext';
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import { ref, child, get  } from "firebase/database";
import {database} from '../../firebase';
import { MOVIES__section, MOVIE__div, PHOTO_MOVIE__div, INFO__div, ADD__button, CONTAINER__div, CONTENT_BTN } from "../../components/homeComp/styles";

import {Watch} from '../../assets/watch.jsx';
import {NoWatch} from '../../assets/notwatch.jsx';

export default function Collectio() {
    const { user } = useAuth();
    const paramsRouter = useRouter().query.collection;
    const [data, setData] = useState(null);

    useEffect(() => { 
        if (paramsRouter && user) {
            const dbRef = ref(database);
            console.log("key", paramsRouter)
            get(child(dbRef, `users/${user.uid}/collections/${paramsRouter}`)).then(snapshot => {
                if (snapshot.exists()) {
                    let moviesArray = [];
                    Object.entries(snapshot.val().movies).forEach(([key, value]) => moviesArray.push({key, ...value}));
                    setData(moviesArray);
                    console.log(moviesArray);
                } else {
                    console.log("No data available");   
                }
            }).catch(error => {console.log(error)});
        }
    },[paramsRouter, user]);

    return (
        <>
            <Head>
                <title>Colección</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <CONTAINER__div>

                {/* <INFO_COLLECTION__section>

    </INFO_COLLECTION__section> */}
                <MOVIES__section>
                    {
                        data ?
                        data.map((movie, index)=>
                            <MOVIE__div key={index}>
                                <PHOTO_MOVIE__div>
                                    <Image src={`https://www.themoviedb.org/t/p/w220_and_h330_face${movie.dataMovie.poster_path}`} alt="img" width="100" height="100" />
                                </PHOTO_MOVIE__div>
                                <INFO__div>
                                    <h4>{movie.dataMovie.title}</h4>
                                    <p>{
                                        movie.dataMovie.title.length <=12 ?
                                        `${movie.dataMovie.overview.slice(0, 70)}...`
                                        :`${movie.dataMovie.overview.slice(0, 50)}...`
                                    }</p>
                                </INFO__div>
                                <CONTENT_BTN>
                                    <ADD__button color="#FF375A">-</ADD__button>
                                    <ADD__button>
                                        <Watch/>
                                    </ADD__button>
                                </CONTENT_BTN>
                            </MOVIE__div>
                        )
                        : <p>No hay peliculas en esta colección</p>
                        }
                </MOVIES__section>
            </CONTAINER__div>
            
        </>
    )
}