import Head from 'next/head'
import { useAuth } from './context/authContext';
import Link from 'next/link';
import HeaderApp from '../components/header/header';
import Headerprofile from '../components/headerProfile/headerProfile';

export default function Profile() {

    const { user } = useAuth();
    console.log(user);

    return (
        <>
            <Head>
                <title>Profile</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            {
                user ?
                <>
                    <HeaderApp>Mi perfil</HeaderApp>
                    <Headerprofile />
                </>
                : <div>
                    <p>Inicia sesión con Google</p>
                    <Link href="/login">Ir</Link>
                </div>
            }
        </>
    )
}
