import Head from 'next/head'
import { useAuth } from '../components/context/authContext';
import Link from 'next/link';
import HeaderApp from '../components/header/header';
import Headerprofile from '../components/headerProfile/headerProfile';
import { Challenge } from '../components/challenge';
import { useEffect, useState } from 'react';
import {database} from '../firebase';
import { ref, child, get  } from "firebase/database";
import { Collections } from '../components/collections';

export default function Profile() {
    const { user } = useAuth();
    const [collections, setcollections] = useState(null);
    const [challenge, setChallenge] = useState(null);

    useEffect(()=>{
        const dbRef = ref(database);

        if (user) {
            get(child(dbRef, `users/${user.uid}`)).then(snapshot => {
                if (snapshot.exists()) {
                    let collectionsArray = [];
                    Object.entries(snapshot.val().collections).forEach(([key, value]) => collectionsArray.push({key, ...value}));
                    setcollections(collectionsArray);
                    setChallenge(snapshot.val().challenge);
                } else {
                    console.log("No data available");
                }
            }).catch(error => {console.log(error)});
        }
    },[user]);

    return (
        <>
            <Head>
                <title>Profile</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            {
                user ?
                <>
                    <HeaderApp>Mi perfil</HeaderApp>
                    <Headerprofile setColl={setcollections} />
                    <Challenge challe={challenge} setChan={setChallenge} />
                    <Collections collec={collections} />
                </>
                : <div>
                    <p>Inicia sesión con Google</p>
                    <Link href="/login">Ir</Link>
                </div>
            }
        </>
    )
}
